### ISSUE TITLE
Running latest on 1.8.9

### ISSUE THREAD

**Issue by madtomic** [ThePhilderbeast/AutoPickup#12]
http://pastebin.com/Gne3tkCQ

Please add support if not. Thank you!

**Comment by ThePhilderbeast** [comment]
5.x only supports minecraft 1.11.2 you will need to update your server

**Comment by Matt80000** [comment]
So you never have plans of making an updated 1.8.9 version?  There are still a lot of people who use that version.

**Comment by ThePhilderbeast** [comment]
nope. i have no plans of going backwards in versions

**Comment by ThePhilderbeast** [comment]
it should compile find against 1.8.9 however so if you cant update you coild try to compile it yourself for 1.8.9
