### ISSUE TITLE
config file changes not being saved 

### ISSUE THREAD

**Issue by GranpaGamer** [ThePhilderbeast/AutoPickup#13]
this is the config from server Ive tried to edit it several times and it always changes back. Im trying to change the autoxp to false. Also want to change drop item on full inventory to false.

Infinity Pick: false
Mob:
  AutoXP: true
  AutoPickup: true
AutoSmelt Compat Mode: true
Block AutoXP: true
Auto Chest: true
Full Inventory:
  Delete Item: true
  Warn: true
Gui:
  Contact Info: true
Allow BlockGui Permission: false
AutoBlock Quartz: true

**Comment by ThePhilderbeast** [comment]
I am unable to replicate this, can you please confirm you are on the latest version of this plugin?

**Comment by GranpaGamer** [comment]
i have uninstalled it and reloaded and it seems to be working now I might have gotten an older version

**Comment by ThePhilderbeast** [comment]
not a problem ill close this off then
