### ISSUE TITLE
Skulls / Dragon Heads Not Entering Inventory Properly

### ISSUE THREAD

**Issue by NolanMC** [ThePhilderbeast/AutoPickup#15]
How to produce this issue: Turn on Auto Pickup, and hit a skull with custom textures, or mob heads (Zombie, Creeper, Skeleton, Dragon, Steve head etc.). Skull will enter inventory as a piece of stone. Player Skulls are not afflicted by this issue. 

What Should Happen: Skulls should enter inventory in their original form, and not as stone. 

Reproduced on 3.8 and 5.0.3

**Comment by ThePhilderbeast** [comment]
tested and working corectly on the latest version
