### ISSUE TITLE
ItemSpawnEvent = Infinite Loop

### ISSUE THREAD

**Issue by CeIebrimbor** [ThePhilderbeast/AutoPickup#20]
Latest build for 1.14 (v5.2.3) creates an infinite loop for the ItemSpawnEvent. It's pretty bad, even shuts console off.

Error:
~~https://pastebin.com/KmyPX4JL~~ expired

**Comment by CeIebrimbor** [comment]
@ThePhilderbeast 
Sorry, set my original paste to expire for some dumb reason.

New Error:
https://pastebin.com/WDTgVZPG

Something you can fix? I think it's coming from McMMO's double drops using the ItemSpawnEvent.

**Comment by ThePhilderbeast** [comment]
defiantly an incompatibility between the plugins, Ill take a look at it but its not going to be high priority.

**Comment by ChimpGamer** [comment]
I've experienced the same issue with the plugin multiple times.

**Comment by leasoncre** [comment]
the 2nd pastebin link is expired too, But i may be getting the same error myself:
https://pastebin.com/5B0nWD5E (expires in 1 month) - "Could not pass event ItemSpawnEvent to AutoPickup v5.3.0"
[ Paper 1.15.2 | Win10HostVM | Java8u241 | AP 5.3.0 ]

Plugins list: https://drive.google.com/file/d/1qsUCeUJJfCLeT05vzOFr6tZnPfpGmac6/ (recommend download a copy) [Status: ACTIVE(green) and TEST(Blue) are running, ignore the rest]

**Comment by ThePhilderbeast** [comment]
paper isn't supported and errors on it won't be investigated
