### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by comonier** [ThePhilderbeast/AutoPickup#21]
Hello Friend,

I love your plugin, use it since the old versions, 1.8 etc ... tops the players of my server also love your plugin, I'm having some difficulties here and would like your help to clarify the problem.

I am the owner, and I have all the permissions with which all the options I will speak, work perfectly.

However as much as I give the permissions to the players, it does not work 2 things for them.

**First problem**: the autoblock option is not automatic for the players for example: They mine coal and after mining 9 coals they do not stake in 1 block. Only if they type / autoblock but only those of the inventory will stake, the new mining continues not staking.

**First problem solution**: _

> i did some change on config and it is working now, i think i change:
> Block AutoXP: false ( true to false ) and it does players instant auto some blocks. not all. (quartz still not working.)

_

**Second problem**: Although I have released the option to the toggle command for them to change whether or not they want to use the autopickup option, they continue to take the loot directly in the inventory even with the option off.

**Second problem solution**:
_

> I just understood now that this option is only for blocks, not for mobs drop, however, even with the config option of not deleting items if inventory is full and alert, they are enabled, the player does not receive alerts and the items are deleted if the auto loot for blocks option is turned on. It would be interesting to test this and fix it, and also add the option of auto loot to drop mobs, (not only in config but in gui toggle tb) separate [blocks] and [mobs]

_

**Third problem**, some blocks are not stacking:
in config have option: AutoBlock Quartz: true
but its not autoblock working i have some tests on nether.
should u add lapis-lazuli also.

**Thir problem solution**: 
_

> I just understood now that the autoblock option for quartz only works if the autopickup option of gui [blocks] is on
> 
> still need to solve the lapis lazuli

_

in pex:
`    - -AutoPickup.reload
    - -AutoPickup.BlockGui
    - -AutoPickup.infinity
    - AutoPickup.enabled
    - AutoBlock.enabled
    - -AutoSmelt.enabled
    - -AutoSell.enabled
    - AutoPickup.toggle
    - AutoBlock.toggle
    - -AutoSmelt.toggle
    - -AutoSell.toggle
    - -AutoSmelt.command
    - AutoBlock.command`

in config:
`Infinity Pick: false
Mob:
  AutoXP: true
  AutoPickup: true
AutoSmelt Compat Mode: true
Block AutoXP: true
Auto Chest: true
Full Inventory:
  Delete Item: true
  Warn: true
Gui:
  Contact Info: true
Allow BlockGui Permission: false
AutoBlock Quartz: true
`

What could I change to solve my 3 problems?

**Comment by comonier** [comment]
![image](https://user-images.githubusercontent.com/19571541/60435023-e8a9d500-9bde-11e9-82f2-da4c7cb5efc0.png)

**Comment by comonier** [comment]
![image](https://user-images.githubusercontent.com/19571541/60435059-f8291e00-9bde-11e9-8539-50e295450f63.png)

**Comment by comonier** [comment]
see still not autoblocking

**Comment by comonier** [comment]
Full Inventory:
  Delete Item: false

i think this options is not working. i had my inventory full and still mining more coals and it not drop on ground
`Infinity Pick: false
Mob:
  AutoXP: true
  AutoPickup: true
AutoSmelt Compat Mode: true
Block AutoXP: false
Auto Chest: true
Full Inventory:
  Delete Item: false
  Warn: true
Gui:
  Contact Info: false
Allow BlockGui Permission: true
AutoBlock Quartz: true`

**Comment by comonier** [comment]
quartz is not auto-block working how add it ?

**Comment by comonier** [comment]
can you add an option and edit info on gui panel, 

autopickup toggle [blocks]
autppickup toggle [mobs]

for players also? and add permissions for that ?

**Comment by ThePhilderbeast** [comment]
can you please put your config in here retaining all the formatting, its a Yaml file so the indenting is important to how it is read.

**Comment by ThePhilderbeast** [comment]
closing due to config not being provided, feel free to reopen with the config file included
