### ISSUE TITLE
AutoSmelt = false Ignored

### ISSUE THREAD

**Issue by eiachh** [ThePhilderbeast/AutoPickup#23]
Straight forward ignores the autosmelt option. It's always true. 

5.2.3

Edit: it just ignores the config file ingame you can set it up.

**Comment by ThePhilderbeast** [comment]
can you please attach your config file with all formatting preserved

**Comment by eiachh** [comment]
[https://www.dropbox.com/s/yrp2v02nxfuv2gr/Config.yml?dl=0](url)
I dont think anything is missformatted but there

**Comment by ThePhilderbeast** [comment]
ok its been a while since I looked at this, Turning autosmelt off is no in the config file, its part of the permissions system.

you need to set AutoBlock.enabled for the player(s) you want it to be off for.
