### ISSUE TITLE
THE BİG PROBLEM 1.14.4

### ISSUE THREAD

**Issue by successed** [ThePhilderbeast/AutoPickup#24]
When the limit of use of the clothing is full, the curse of attachment is not deleted, it comes directly back to me instead of clothes!

**Comment by ThePhilderbeast** [comment]
please provide more information.

this sounds like its conflicting plugins.

**Comment by successed** [comment]
> please provide more information.
> 
> this sounds like its conflicting plugins.



This item When the limit of use of the clothing is full, not deleted, it comes directly back to me instead of clothes!

İTEM : http://prntscr.com/ojfwee

**Comment by ThePhilderbeast** [comment]
still not helpfull.

please provide a list of ALL plugins, and note the one your using to limit clothing, and your config file, retaining all formatting

**Comment by ThePhilderbeast** [comment]
closing this unless more information is provided.
