### ISSUE TITLE
Big issue

### ISSUE THREAD

**Issue by Achent007** [ThePhilderbeast/AutoPickup#28]
Sometimes i got this very very very big error https://pastebin.com/ijujfvne and after this error my console freeze during a big lot of time and i need to restart my server to fix the console.

Server version : paper-159 1.14.4
Plugin version : 5.2.3

**Comment by Achent007** [comment]
My config options :
Infinity Pick: false
Mob:
  AutoXP: false
  AutoPickup: false
AutoSmelt Compat Mode: true
Block AutoXP: false
Auto Chest: false
Full Inventory:
  Delete Item: false
  Warn: true
Gui:
  Contact Info: true
Allow BlockGui Permission: false
AutoBlock Quartz: false

**Comment by ThePhilderbeast** [comment]
Paper is not a supported platform
