### ISSUE TITLE
ItemSpawnEvent Laggy

### ISSUE THREAD

**Issue by successed** [ThePhilderbeast/AutoPickup#31]
İ have big laggy..

Check this out : http://prntscr.com/p65x92

Can you fix this problem ?

**Comment by ThePhilderbeast** [comment]
not sure what the issue is here, you will need to provide more details.

but over 800k calls looks like more the problem then the performance of the call it self

**Comment by successed** [comment]
i have i9900k cpu and nwme disc mean. İ need more performance.

**Comment by ThePhilderbeast** [comment]
you will have to look elsewhere for the problem, its not this plugin.
