### ISSUE TITLE
Add support, Paper spigot.

### ISSUE THREAD

**Issue by successed** [ThePhilderbeast/AutoPickup#34]
Can you add paper spigot support please ?

**Comment by ThePhilderbeast** [comment]
there are no plans to support paper spigot at this time

**Comment by successed** [comment]
> there are no plans to support paper spigot at this time

Just add plan.

**Comment by IITFA** [comment]
I second this, please bring paper support. I've spent the last half hour trying to figure out why this plugin isn't working on my paper server, then found this.

**Comment by successed** [comment]
we need update 1.15.1 and paper support...

**Comment by ThePhilderbeast** [comment]
paper wont be offially supported unless someone it willing to do that them selves.

1.15.X support will be done when i have a chance to work on it.
