### ISSUE TITLE
What is the last version working with 1.8.X?

### ISSUE THREAD

**Issue by DevJorgeMCS** [ThePhilderbeast/AutoPickup#35]
Just a question.
Im using 3.9 but i don't know what should use.

**Comment by ThePhilderbeast** [comment]
you should update your server. 1.8 is not support anymore

**Comment by DevJorgeMCS** [comment]
I KNOW that NO SUPPORT for 1.8 anymore but was a simple question. 
You didn't answer because you didn't want to. thanks for nothing
