### ISSUE TITLE
Autoblock: Lapis

### ISSUE THREAD

**Issue by leezallen** [ThePhilderbeast/AutoPickup#49]
Autoblock function does not appear to be working with lapis. Is it possible to add it?

**Comment by ThePhilderbeast** [comment]
Lapis should work, please post your config and and errors your getting

**Comment by leezallen** [comment]
Have attached all of my configs to this post (renamed as .txt as it would not let me upload YML files)

[Advanced Fortune.txt](https://github.com/ThePhilderbeast/AutoPickup/files/4240109/Advanced.Fortune.txt)
[Config.txt](https://github.com/ThePhilderbeast/AutoPickup/files/4240110/Config.txt)
[Messages.txt](https://github.com/ThePhilderbeast/AutoPickup/files/4240111/Messages.txt)
[Smelt Blacklist.txt](https://github.com/ThePhilderbeast/AutoPickup/files/4240112/Smelt.Blacklist.txt)
[World Blacklist.txt](https://github.com/ThePhilderbeast/AutoPickup/files/4240113/World.Blacklist.txt)

. Should have mentioned earlier that I have tried this on version 1.14.4 and 1.15.2 (using Paper). 

Not receiving any error messages at all, Everything works for other ores as expected except Lapis just doesn't do anything... If I have a batch of lapis in my inventory and then run /autopickup and click the Block my items menu I just get a "Nothing in your inventory could be auto blocked" message.

**Comment by raider9714** [comment]
Same here, lapis definitely doesn't get auto-blocked.

**Comment by ThePhilderbeast** [comment]
fixed in Dev, will be in the next release
