### ISSUE TITLE
Can't turn delete item off

### ISSUE THREAD

**Issue by Branflakes22** [ThePhilderbeast/AutoPickup#51]
When I try to turn off delete item when the player's inventory is full it doesn't work. When I restart my server the config has reset it back to true. My server is running 1.15.2 and I'm using the latest release that isn't the beta. There are no errors in my console.

**Comment by Lunatic-Gamer** [comment]
I further have this issue, any fixes?

**Comment by ThePhilderbeast** [comment]
the beta version has the fix for this, i need to do a full release still.
