### ISSUE TITLE
CONFIG FILE ALWAYS RESETS

### ISSUE THREAD

**Issue by raider9714** [ThePhilderbeast/AutoPickup#57]
As the title says, the config files are always being reset so this makes it so you have to keep all the options on. Making nether quartz into blocks every time, which means I can't use nether quartz at all because they are turned into building blocks only.

Also with deleting items on full inventory, which sucks because if you have a full inventory and find diamonds they just get deleted... And don't get me started with the auto smelt.

**Comment by ThePhilderbeast** [comment]
this is fixed in the beta release
