### ISSUE TITLE
Breaking stone Results in getting stone instead of cobble.

### ISSUE THREAD

**Issue by Treezaow** [ThePhilderbeast/AutoPickup#62]
If anyone has the solution please post it, this is very annoying because this is the only plugin that i can use that does autopickup.
i do realize you can go into the blacklist but i don't know what to type or put in there to fix it.

**Comment by ThePhilderbeast** [comment]
is auto smelt on?

**Comment by ThePhilderbeast** [comment]
closing this as a duplicate of #50
