### ISSUE TITLE
Config file resets every startup

### ISSUE THREAD

**Issue by hihey560** [ThePhilderbeast/AutoPickup#69]
Every time I start my server up, the config file resets. I just want to keep delete items on false but it never remains that way.

**Comment by ThePhilderbeast** [comment]
please post the version are using, server version and other plugins installed.

**Comment by MatusGoc** [comment]
I can confirm I get the same behavior.
Version: 5.4.0
Server: git-Spigot-988b411-1f4693a (MC: 1.16.3) (Implementing API version 1.16.3-R0.1-SNAPSHOT)
Other plugins: (all latest versions at the time of writing)
- [Death coordinates](https://www.spigotmc.org/resources/deathcoordinates-1-8-1-16.43318/)
- [Fast leaf decay](https://dev.bukkit.org/projects/fastleafdecay)
- [GtzDoors](https://www.spigotmc.org/resources/gtzdoors-double-doors-and-door-knock.37517/)
- [LuckPerms](https://luckperms.net/)
- [Minepacks](https://www.curseforge.com/minecraft/bukkit-plugins/minepacks)
- [Simple player tracker](https://dev.bukkit.org/projects/simple-player-tracker)
- [Set homes](https://www.curseforge.com/minecraft/bukkit-plugins/set-homes)
- [Silkspawners](https://dev.bukkit.org/projects/silkspawners)
- [Single player sleep 2](https://www.curseforge.com/minecraft/bukkit-plugins/singleplayersleep2)
- [Timber plugin](https://www.curseforge.com/minecraft/bukkit-plugins/timber-plugin)
- [Twerktree](https://www.spigotmc.org/resources/twerktree.35496/)
- [Vein miner](https://www.curseforge.com/minecraft/bukkit-plugins/vein-miner)

**Comment by ThePhilderbeast** [comment]
I am unable to reproduce this.

**Comment by ThePhilderbeast** [comment]
closing for this for now as I cant reproduce this and no info has been provided, if more info is provided this can be reopened
