### ISSUE TITLE
Conflict with Slimefun plugin

### ISSUE THREAD

**Issue by Zireaphus** [ThePhilderbeast/AutoPickup#71]
When you activate the AutoPickUp plugin and break a Slimefun plugin machine it comes into the inventory as a vanilla item, however when you disable AutoPickUp and break the same machine, nothing happens, it remains a Slimefun item. One of the plugin's devs stated the following: "This is an issue on their side. Tell them to preserve the itemstack's metadata. Actually they might just get the items material... in which case that cant be fixed either way, not a slimefun fix ". I don't know if you know the Slimefun plugin and its addons.

**Comment by ThePhilderbeast** [comment]
the metadata isnt being changed on our side, more detail will be needed to look at this.
