### ISSUE TITLE
When you change and reload the config file, it always returns to its default settings.

### ISSUE THREAD

**Issue by regamecouter** [ThePhilderbeast/AutoPickup#78]
It's the same situation as https://github.com/ThePhilderbeast/AutoPickup/issues/69 and https://github.com/ThePhilderbeast/AutoPickup/issues/57 

To prevent canned items from being deleted when the inventory is full
I modified Config.yml file  Delete Item : disabled and save the file
but reload the plugin, it reverts back to the enabled state.

So when I open the editing window and reload, it says that the config file has changed in the editing window.

I'm using the latest version of the spigot 1.16.4 , and I'm using the latest version of the autopickup plugin.

If I reload it into a plugman plugin (https://github.com/r-clancy/PlugMan) , will the config go back to default?

**Comment by ThePhilderbeast** [comment]
and just like the referanced tickets, i still cant reproduce this, please provide the setup that allows this to be reproduced..

**Comment by regamecouter** [comment]
Resolved using plugman plugin.

You load the autopickup Plugin and plugman Plugin
change the autopickup Plugin config, then save it.
unload autopickup to the plugman Plugin,
and reload it into the plugman Plugin to save the saved settings.
If you save it and reload it directly into the plugman Plugin, it reverts to its default settings.

Summary : After saving the config, you must unload them to plugin and reload them.
Reloading as soon as you save returns you to the default settings.
